variables:
  IMAGE_NAME: zohiddev/medium_api_gateway
  IMAGE_TAG: latest


stages: 
  - build
  - deploy

build-image: 
  stage: build
  image: docker:20.10.16
  services: 
    - docker:20.10.16-dind
  variables: 
    DOCKER_TLS_CERTDIR: "/certs"
  before_script:
    - docker login -u $REGISTRY_USER -p $REGISTRY_PASS
  script:
    - docker build -t $IMAGE_NAME:$IMAGE_TAG .
    - docker push $IMAGE_NAME:$IMAGE_TAG
  only:
    - main

deploy:
  stage: deploy
  before_script:
    - chmod 400 $SSH_KEY
  script:
    - ssh -o StrictHostKeyChecking=no -i $SSH_KEY ubuntu@3.70.225.34 "
        docker login -u $REGISTRY_USER -p $REGISTRY_PASS  &&
        docker pull $IMAGE_NAME:$IMAGE_TAG &&
        cd medium &&
        make up"
  only:
    - main
